name: Testing workflow file 2

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  check-pinning-dates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Output something
        run: echo 'THIS IS WORKFLOW FILE 2 in WORKFLOW GROUP 2'