name: Child

on:
  workflow_call:
    inputs:
      key_vault_name:
        description: 'Name of key vault'
        type: string
        required: true
      key_vault_objects:
        description: 'An array of objects with each object containing info on key vault secrets'
        type: string
        required: true

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:

      - name: Parse JSON Array and Fetch Secrets
        run: |
          echo '${{ inputs.key_vault_objects }}' > secrets.json
          secrets=$(jq -c '.[]' secrets.json)

          while IFS= read -r item; do
            secret_name=$(echo "$item" | jq -r '.secretName')
            env_var=$(echo "$item" | jq -r '.envVar')

            echo '$(az keyvault secret show --name "${secret_name}" --vault-name "${{ inputs.key_vault_name }}" --query value -o tsv)'
            SECRET_VALUE=test

            echo "::add-mask::$SECRET_VALUE" # Mask the secret in logs
            echo "$env_var=$SECRET_VALUE" >> $GITHUB_ENV # Set as an environment variable
          done <<< "$secrets"