name: Child

on:
  workflow_call:
    inputs:
      github_env_vars:
        description: 'An array of strings to determine which GitHub environment variables to pull in'
        type: string
        required: true

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output input
        run: |
          echo ${{ inputs.github_env_vars }}

      - name: Set Dynamic GitHub Environment Variables
        if: ${{ inputs.github_env_vars }}
        run: |
          if [ -z "${{ inputs.github_env_vars }}" ]; then
            echo "No environment variables provided."
            exit 0
          fi 

          # Save input to a JSON file
          echo '${{ inputs.github_env_vars }}' > github_env_vars.json

          # Debug output to verify content
          cat github_env_vars.json

          # Loop through each variable from the JSON array
          jq -c '.[]' github_env_vars.json | while IFS= read -r var_name; do
            # Remove potential quotes from the variable name
            var_name=$(echo "$var_name" | tr -d '"')

            # Access the GitHub environment variable
            var_value=$(printenv "$var_name")
            
            # If the variable is not empty, add it to GITHUB_ENV
            if [ -n "$var_value" ]; then
              echo "Setting $var_name=$var_value"
              echo "$var_name=$var_value" >> $GITHUB_ENV
            else
              echo "Warning: $var_name is not set"
            fi
          done
      
      - name: Output Env Vars
        run: |
          env | sort
