name: Child

on:
  workflow_call:
    inputs:
      array_input:
        description: 'This is the test var 2'
        type: string
        required: true

permissions:
  issues: write
  contents: read

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Parse JSON and output inputs
        run: |
          echo "var 2 --> "
          echo '${{ inputs.array_input }}' > input.json
          arr=$(jq -r '.[]' input.json)
          for item in $arr; do
            echo "Item: $item"