name: Child

on:
  workflow_call:
    inputs:
      ENV_VAR_ONE:
        description: 'Test variable'
        type: string
        required: false
      ENV_VAR_TWO:
        description: 'Another variable'
        type: string
        required: false
      ENV_VAR_THREE:
        description: 'Example variable'
        type: string
        required: false
      test:
        description: 'test'
        type: string
        required: true

jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Output all inputs
        run: |
          echo "Input One: ${{ inputs.ENV_VAR_ONE }}"
          echo "Input Two: ${{ inputs.ENV_VAR_TWO }}"
          echo "Input Three: ${{ inputs.ENV_VAR_THREE }}"
          echo "Input Four: ${{ inputs.test }}"

      - name: Set a env var
        run: |
          echo "TEST_ENV_VAR=1111" >> $GITHUB_ENV

      - name: Iterate over inputs
        run: |
          input_value="${{ github.event.inputs }}"
          echo "$input_name: $input_value"

      # - name: Dynamically Set Environment Variables
      #   run: |
      #     # Loop through all the inputs dynamically
      #     for input_name in "${!INPUT_@}"; do
      #       value="${!input_name}"
      #       if [ -n "$value" ]; then
      #         var_name="${input_name#INPUT_}"  # Remove the 'INPUT_' prefix
      #         # var_name=$(echo "$var_name" | tr '[:upper:]' '[:lower:]')  # Convert to lowercase if needed
      #         echo "Setting environment variable: $var_name=$value"
      #         echo "$var_name=$value" >> $GITHUB_ENV
      #       fi
      #     done

      - name: Output all environment variables
        run: |
          echo "Listing all environment variables:"
          printenv 