name: Child

on:
  workflow_call:
    inputs:
      ENV_VAR_ONE:
        description: '[build-var] Test variable'
        type: string
        required: false
      ENV_VAR_TWO:
        description: '[workflow-var] Another variable'
        type: string
        required: false
      # Can I set an env var here?
      ENV_VAR_THREE:
        description: '[build-var] Example variable'
        type: string
        required: false
      test:
        description: 'test'
        type: string
        required: true

jobs:
  set-env-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Output all inputs
        run: |
          echo "Input One: ${{ inputs.ENV_VAR_ONE }}"
          echo "Input Two: ${{ inputs.ENV_VAR_TWO }}"
          echo "Input Three: ${{ inputs.ENV_VAR_THREE }}"
          echo "Input Four: ${{ inputs.test }}"

      - name: Set a env var
        run: |
          echo "TEST_ENV_VAR=1111" >> $GITHUB_ENV

      - name: Set inputs as environment variables
        run: |
          inputs='${{ toJson(inputs) }}'
          echo "$inputs" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' | while IFS= read -r line; do
            echo "Setting $line"
            echo "$line" >> $GITHUB_ENV
          done

      - name: Output all environment variables
        run: |
          echo "Listing all environment variables:"
          printenv 