name: Child

on:
  workflow_call:
    inputs:
      github_env_var:
        description: 'A variable'
        type: string
        required: true

jobs:
  test-job:
    runs-on: ubuntu-latest
    environment: Develop
    steps:
      - name: Output Env Vars
        run: |
          echo ${{ inputs.github_env_var }}