name: Parent

on:
  workflow_dispatch:

jobs:
  run-child:
    uses: ./.github/workflows/child.yml
    with:
      test-var-1: Develop
      array_input: ${{ toJson(env.ARRAY) }}
    env:
      ARRAY: '["one", "two", "three"]'