name: Test stuff

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Output something
        run: echo "This is something"